version: '3.8'
services:
  vintage_1:
    image: miketang84/vintage:20250705
    restart: always
    ports:
      - "8001:8001"
    environment:
      - RUST_LOG=info
    command: vintage -c /vintage/config.yml
    depends_on:
      - cache_1
      - db_1
    
  dtomcat_1:
    image: miketang84/dtomcat:20250705
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=cache_1:6379
      - DB_HOST=db_1:5432
      - REDIS_URL=redis://cache_1:6379
      - DB_URL=postgresql://postgres:postgres@db_1:5432/#proto?sslmode=disable
      - OUTBOUND_HOST1=https://xxx.com
      - OUTBOUND_HOST2=https://yyy.com
      - OUTBOUND_HOST3=https://zzz.com
      - RUST_LOG=info
      - SPIN_ENV_XXX=XXX
    command: dtomcat
    depends_on:
      - cache_1
      - db_1
      - vintage_1

  db_1:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=${POSTGRES_DBNAME}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "logging_collector=off"
      - "-c"
      - "log_min_messages=DEBUG1"
      - "-c"
      - "log_min_error_statement=ERROR"
    volumes: 
      # - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./init_pg.sql:/docker-entrypoint-initdb.d/init_pg.sql
    depends_on:
      - cache_1

  cache_1:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 
    #volumes: 
      # - cache:/data

