version: '3.7'
services:
  subnode_1:
    image: miketang84/eightfish-subnode:20230623
    restart: always
    ports:
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"
    command: eightfish-subnode --chain=dev --alice -d /data --unsafe-rpc-external --unsafe-ws-external --rpc-cors all --validator --node-key 0000000000000000000000000000000000000000000000000000000000000001
    volumes:
      - ./data/substrate-data:/data
    
  subxtproxy_1:
    image: miketang84/eightfish-subxtproxy:20230623
    restart: always
    environment:
      - REDIS_URL=redis://cache_1:6379
      - SUBNODE_RPC=ws://subnode_1:9944
    command: subxtproxy
    depends_on:
      - cache_1
      - subnode_1

  http_gate_1:
    image: miketang84/eightfish-http_gate:20230623
    restart: always
    ports:
      - "3000:3000"
    command: spin up -f http_gate_spin.toml --listen 0.0.0.0:3000 -e REDIS_URL=redis://cache_1:6379
    depends_on:
      - cache_1

  gutp_app_1:
    image: gutp-app-a
    restart: always
    command: spin up -f gutp_app_spin.toml -e REDIS_URL=redis://cache_1:6379 -e DB_URL="host=db_1 user=postgres password=postgres dbname=spin_dev sslmode=disable"
    depends_on:
      - cache_1
      - db_1
      - subnode_1
      - subxtproxy_1

  db_1:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spin_dev
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes: 
      - ./data/postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./init_pg.sql:/docker-entrypoint-initdb.d/init_pg.sql

  cache_1:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 
    volumes: 
       - ./data/redis-data:/data
