version: '3.7'
services:
  vintage_1:
    image: vintage
    restart: always
    ports:
      - "8000:8000"
    volumes: 
      - ./data/blockchain-data:/data
      - ./vintage:/vintage
    depends_on:
      - cache_1
  
  http_gate_1:
    image: miketang84/eightfish-http_gate:20230623
    restart: always
    ports:
      - "3000:3000"
    command: spin up -f http_gate_spin.toml --listen 0.0.0.0:3000 -e REDIS_URL=redis://cache_1:6379
    depends_on:
      - cache_1

  gutp_app_1:
    image: gutp-app-a
    restart: always
    command: SPIN_VARIABLE_REDIS_HOST="cache_1" SPIN_VARIABLE_PROTO_ID="gutp" spin up -f spin_gutp.toml -e REDIS_URL_ENV="redis://cache_1:6379" -e DB_URL_ENV="host=db_1 user=postgres password=postgres dbname=gutp sslmode=disable"
    depends_on:
      - cache_1
      - db_1

  db_1:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gutp
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes: 
      - ./data/postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./init_pg.sql:/docker-entrypoint-initdb.d/init_pg.sql

  cache_1:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 
    volumes: 
       - ./data/redis-data:/data
