dev_mode: true
blockchain:
  db_path: /data/blockchain.db
proxy:
  redis_addr: redis://cache_1:6379
node:
  block_interval: 1000
  name: Node1
  listen_addr: 172.28.1.1:8001
  propose_weight: 1
  vote_weight: 1
  peers:
    - name: Node2
      address: 172.28.1.2:8002
      propose_weight: 1
      vote_weight: 1
    - name: Node3
      address: 172.28.1.3:8003
      propose_weight: 1
      vote_weight: 1
    - name: Node4
      address: 172.28.1.4:8004
      propose_weight: 1
      vote_weight: 1