spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A redis application."
name = "gutp"
version = "0.1.0"

[variables]
redis_url = { required = true }
db_url = { required = true }

[application.trigger.redis]
address = "{{ redis_url }}"

[[trigger.redis]]
channel = "proxy2spin"          # the channel that the trigger subscribes to
component = "gutp"


[component.gutp]
source = "target/wasm32-wasi/release/gutp.wasm"
allowed_outbound_hosts = ["{{ redis_url }}", "{{db_url}}"]
#environment = { DB_URL = "host=localhost user=postgres password=123456 dbname=spin_dev sslmode=disable", REDIS_URL = "redis://127.0.0.1:6379"}

[component.gutp.build]
command = "cargo build --target wasm32-wasi --release"
