spin_manifest_version = 2

# General identification information
[application]
name = "gutp"
version = "1.0.0"
description = "The General User's Text Persistence protocol."

[variables]
proto_id = { required = true }  # will be filled out in ENV

[[trigger.redis]]
address = "redis://localhost:6379"
channel = "vin2worker:{{proto_id}}"
component = "gutp"

[component.gutp]
description = "The component GUTP."
source = "target/wasm32-wasi/release/gutp.wasm"

[component.gutp.variables]
proto_id = "{{ proto_id }}"

# How to build the Wasm module from source
[component.gutp.build]
command = "cargo build --target wasm32-wasi --release"
