[package]
name = "gutp-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eightfish = {path = "../../eightfish"}
eightfish-derive = {path = "../../eightfish/eightfish-derive"}

